name: ci
on: [push]

permissions:
  contents: read

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.34.0"
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: api
